enableVolumeResizing: true
enableVolumeSnapshot: false

tolerateAllTaints: true

tolerations:
  - operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - ebs-csi-controller
        topologyKey: "kubernetes.io/hostname"

# If set, add pv/pvc metadata to plugin create requests as parameters.
extraCreateMetadata: false

node:
  nodeSelector: {}
  podAnnotations:
    iam.amazonaws.com/role: k8s_ebs_csi_driver
  tolerateAllTaints: true
  tolerations: []

serviceAccount:
  controller:
    annotations: {}
  snapshot:
    annotations: {}
    