name: voa-k3s-test
kind: Project
backend: aws-backend
variables:
  organization: shalb # sample global variable
  region: eu-central-1
  state_bucket_name: cdev-states # create and set your s3 bucket here
#exports:
#  AWS_PROFILE: cluster-dev # comment since it could lead to misunderstanding during cli interact
#  CDEV_TF_BINARY: /usr/local/bin/terraform-0.14.9 # optional set of TF version